### ISSUE TITLE
Requesting login credentials when enabling sandbox mode

### ISSUE THREAD

**Issue by brookmg** [YenePay/yenepay.sdk.android#2]
As stated in the README.md of this sdk, I enabled the sandbox feature while i debug my app. But opens a webpage that requires a login to be filled to proceed. 

Disabling the sandbox led to an error in which the merchant id and the client id cannot be the same. Basically I can't test this on my own device or my own account.

**Comment by SisayKelkle** [comment]
Sorry Brook for our late response.

You need to go to https://sandbox.yenepay.com and create both merchant and buyer accounts for testing. You need also to add balance to your buyer account so that you will be able to pay for your test transactions. This all can done through our sandbox website. Please find more information on our community website https://community.yenepay.com/docs/yenepay-sandbox/

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by brookmg** [comment]
Thanks for the reply sisay. I have managed to create sandbox accounts.
